// Mozilla User Preferences

// DO NOT EDIT THIS FILE.
//
// If you make changes to this file while the application is running,
// the changes will be overwritten when the application exits.
//
// To change a preference value, you can either:
// - modify it via the UI (e.g. via about:config in the browser); or
// - set it within a user.js file in your profile.

user_pref("app.normandy.first_run", false);
user_pref("app.normandy.startupRolloutPrefs.network.cookie.cookieBehavior", 4);
user_pref("app.normandy.user_id", "59ab1ce2-efd5-4201-b4e5-d001c02cd113");
user_pref("app.update.lastUpdateTime.addon-background-update-timer", 1575910963);
user_pref("app.update.lastUpdateTime.blocklist-background-update-timer", 1575911083);
user_pref("app.update.lastUpdateTime.browser-cleanup-thumbnails", 1575910483);
user_pref("app.update.lastUpdateTime.recipe-client-addon-run", 1575910723);
user_pref("app.update.lastUpdateTime.search-engine-update-timer", 1575910603);
user_pref("app.update.lastUpdateTime.services-settings-poll-changes", 1575910843);
user_pref("app.update.lastUpdateTime.telemetry_modules_ping", 0);
user_pref("app.update.lastUpdateTime.xpi-signature-verification", 0);
user_pref("browser.bookmarks.restore_default_bookmarks", false);
user_pref("browser.cache.disk.amount_written", 4464);
user_pref("browser.cache.disk.capacity", 1048576);
user_pref("browser.cache.disk.filesystem_reported", 1);
user_pref("browser.contentblocking.category", "standard");
user_pref("browser.laterrun.bookkeeping.profileCreationTime", 1575910457);
user_pref("browser.laterrun.bookkeeping.sessionCount", 1);
user_pref("browser.laterrun.enabled", true);
user_pref("browser.migration.version", 81);
user_pref("browser.newtabpage.activity-stream.impressionId", "{26af6952-5ce7-4d50-947d-2edfe5b6d4ad}");
user_pref("browser.newtabpage.storageVersion", 1);
user_pref("browser.pageActions.persistedActions", "{\"version\":1,\"ids\":[\"bookmark\",\"pinTab\",\"bookmarkSeparator\",\"copyURL\",\"emailLink\",\"addSearchEngine\",\"sendToDevice\",\"pocket\",\"screenshots_mozilla_org\"],\"idsInUrlbar\":[\"pocket\",\"bookmark\"]}");
user_pref("browser.pagethumbnails.storage_version", 3);
user_pref("browser.safebrowsing.provider.google4.lastupdatetime", "1575910513140");
user_pref("browser.safebrowsing.provider.google4.nextupdatetime", "1575912284140");
user_pref("browser.safebrowsing.provider.mozilla.lastupdatetime", "1575910465547");
user_pref("browser.safebrowsing.provider.mozilla.nextupdatetime", "1575914065547");
user_pref("browser.search.region", "IN");
user_pref("browser.shell.mostRecentDateSetAsDefault", "1575910460");
user_pref("browser.slowStartup.averageTime", 25117);
user_pref("browser.slowStartup.samples", 1);
user_pref("browser.startup.homepage_override.buildID", "20190718161435");
user_pref("browser.startup.homepage_override.mstone", "68.0.1");
user_pref("browser.startup.lastColdStartupCheck", 1575910460);
user_pref("browser.uiCustomization.state", "{\"placements\":{\"widget-overflow-fixed-list\":[],\"nav-bar\":[\"back-button\",\"forward-button\",\"stop-reload-button\",\"home-button\",\"customizableui-special-spring1\",\"urlbar-container\",\"customizableui-special-spring2\",\"downloads-button\",\"library-button\",\"sidebar-button\",\"fxa-toolbar-menu-button\"],\"toolbar-menubar\":[\"menubar-items\"],\"TabsToolbar\":[\"tabbrowser-tabs\",\"new-tab-button\",\"alltabs-button\"],\"PersonalToolbar\":[\"personal-bookmarks\"]},\"seen\":[\"developer-button\"],\"dirtyAreaCache\":[\"nav-bar\"],\"currentVersion\":16,\"newElementCount\":2}");
user_pref("browser.urlbar.placeholderName", "Google");
user_pref("datareporting.policy.dataSubmissionPolicyAcceptedVersion", 2);
user_pref("datareporting.policy.dataSubmissionPolicyNotifiedTime", "1575910462054");
user_pref("devtools.onboarding.telemetry.logged", true);
user_pref("distribution.canonical.bookmarksProcessed", true);
user_pref("distribution.iniFile.exists.appversion", "68.0.1");
user_pref("distribution.iniFile.exists.value", true);
user_pref("dom.push.userAgentID", "d5cbc406f15645759f55e96397c7b97c");
user_pref("extensions.activeThemeID", "default-theme@mozilla.org");
user_pref("extensions.blocklist.lastModified", "Mon, 09 Dec 2019 12:01:50 GMT");
user_pref("extensions.blocklist.pingCountTotal", 2);
user_pref("extensions.blocklist.pingCountVersion", 2);
user_pref("extensions.databaseSchema", 31);
user_pref("extensions.getAddons.cache.lastUpdate", 1575910993);
user_pref("extensions.getAddons.databaseSchema", 5);
user_pref("extensions.incognito.migrated", true);
user_pref("extensions.lastAppVersion", "68.0.1");
user_pref("extensions.lastPlatformVersion", "68.0.1");
user_pref("extensions.pendingOperations", false);
user_pref("extensions.systemAddonSet", "{\"schema\":1,\"addons\":{}}");
user_pref("extensions.webcompat.perform_injections", true);
user_pref("extensions.webcompat.perform_ua_overrides", true);
user_pref("extensions.webextensions.uuids", "{\"formautofill@mozilla.org\":\"f684162b-b5ce-4fb5-8623-4d93579cfb0b\",\"fxmonitor@mozilla.org\":\"da7807fa-7ef5-4b8f-804d-1db429c0bf38\",\"screenshots@mozilla.org\":\"26349331-4c95-4175-afce-ae684a2b52f5\",\"webcompat-reporter@mozilla.org\":\"755da664-d641-4cec-8b19-d6e3988e6943\",\"webcompat@mozilla.org\":\"c223b7ec-f5c7-4c5f-ad47-d206bde3d9dc\",\"default-theme@mozilla.org\":\"82e4a6fe-cafe-4504-b9bc-dff56bd3622c\",\"google@search.mozilla.org\":\"e43dbf54-8cdb-4a95-bf84-29f2ead03c1e\",\"amazondotcom@search.mozilla.org\":\"046d564e-4845-40cf-969e-1382817327b4\",\"bing@search.mozilla.org\":\"efd8e14b-025e-420b-9c5f-a8a2994b406e\",\"ddg@search.mozilla.org\":\"561f3b1b-2f83-4f78-b369-2102a93d112a\",\"ebay@search.mozilla.org\":\"e03c5395-ccc3-42e1-b9d4-5b2f9c03e847\",\"twitter@search.mozilla.org\":\"ae3dd039-737e-4dbe-8e8b-184eab3a0330\",\"wikipedia@search.mozilla.org\":\"409a8c69-5ff2-4726-be97-ec2e216e31bb\"}");
user_pref("media.gmp.storage.version.observed", 1);
user_pref("network.predictor.cleaned-up", true);
user_pref("pdfjs.enabledCache.state", true);
user_pref("pdfjs.migrationVersion", 2);
user_pref("pdfjs.previousHandler.alwaysAskBeforeHandling", true);
user_pref("pdfjs.previousHandler.preferredAction", 4);
user_pref("places.history.expiration.transient_current_max_pages", 112348);
user_pref("plugin.disable_full_page_plugin_for_types", "application/pdf");
user_pref("privacy.sanitize.pending", "[]");
user_pref("security.sandbox.content.tempDirSuffix", "f2292636-8032-491d-94a1-d95c206c9794");
user_pref("security.sandbox.plugin.tempDirSuffix", "91fa1ba4-75ee-4631-863a-f4781fb09a81");
user_pref("signon.importedFromSqlite", true);
user_pref("toolkit.startup.last_success", 1575910444);
user_pref("toolkit.telemetry.cachedClientID", "1a9a9e8d-1c0d-49be-b32d-fc4707f5d924");
user_pref("toolkit.telemetry.previousBuildID", "20190718161435");
user_pref("toolkit.telemetry.reportingpolicy.firstRun", false);
